Backend: Vitis
ClockPeriod: 5
HLSConfig:
  LayerName:
    add_channel:
      Precision:
        result: fixed<16,6>
      Trace: false
    cluster:
      Precision:
        result: fixed<16,6>
      Trace: false
    concat_all:
      Precision:
        result: fixed<16,6>
      Trace: false
    concat_scalars:
      Precision:
        result: fixed<16,6>
      Trace: false
    conv2d:
      Precision:
        bias: fixed<4,1>
        result: fixed<16,6>
        weight: fixed<4,1>
      Trace: false
    conv2d_act:
      Precision:
        result: ufixed<8,0,RND_CONV,SAT>
      Trace: false
    conv2d_linear:
      Precision:
        result: fixed<16,6>
      Trace: false
    dense_scalars:
      Precision:
        bias: fixed<4,1>
        result: fixed<16,6>
        weight: fixed<4,1>
      Trace: false
    dense_scalars_act:
      Precision:
        result: ufixed<8,0,RND_CONV,SAT>
      Trace: false
    dense_scalars_linear:
      Precision:
        result: fixed<16,6>
      Trace: false
    flatten_vol:
      Precision:
        result: fixed<16,6>
      Trace: false
    merged_dense1:
      Precision:
        bias: fixed<4,1>
        result: fixed<16,6>
        weight: fixed<4,1>
      Trace: false
    merged_dense1_act:
      Precision:
        result: ufixed<8,0,RND_CONV,SAT>
      Trace: false
    merged_dense1_linear:
      Precision:
        result: fixed<16,6>
      Trace: false
    merged_dense2:
      Precision:
        bias: fixed<4,1>
        result: fixed<16,6>
        weight: fixed<4,1>
      Trace: false
    merged_dense2_act:
      Precision:
        result: ufixed<8,0,RND_CONV,SAT>
      Trace: false
    merged_dense2_linear:
      Precision:
        result: fixed<16,6>
      Trace: false
    output:
      Precision:
        result: fixed<8,1,RND_CONV,SAT>
        shift: fixed<16,6>
        slope: fixed<16,6>
      Trace: false
    output_dense:
      Precision:
        bias: fixed<4,1>
        result: fixed<16,6>
        weight: fixed<4,1>
      Trace: false
    output_dense_linear:
      Precision:
        result: fixed<16,6>
      Trace: false
    pool2d_1:
      Precision:
        result: fixed<16,6>
      Trace: false
    y_local:
      Precision:
        result: fixed<16,6>
      Trace: false
    z_global:
      Precision:
        result: fixed<16,6>
      Trace: false
  Model:
    BramFactor: 1000000000
    Precision: fixed<16,6>
    ReuseFactor: 1
    Strategy: Latency
    TraceOutput: false
IOType: io_parallel
InputData: null
KerasModel: !keras_model '/home/youeric/PixelML/SmartpixReal/Muon_Collider_Smart_Pixels/eric/model3_quantized_4w0i_hyperparameter_results_20260221_131507/hls_outputs/hls_model_trial_1/keras_model.h5'
OutputDir: /home/youeric/PixelML/SmartpixReal/Muon_Collider_Smart_Pixels/eric/model3_quantized_4w0i_hyperparameter_results_20260221_131507/hls_outputs/hls_model_trial_1
OutputPredictions: null
Part: xc7z020clg400-1
ProjectName: myproject
Stamp: 8AaaaA66
Version: 1.0.0
